### ISSUE TITLE
BepInEx Error

### ISSUE THREAD

**Issue by Medatur76** [NuclearPowered/Reactor#48]
Hello, I'm starting to make an among us imposter role mod and it said to start I need to install the Reactor.dll file, so I did and this is what came out of the console:
[Error  :   BepInEx] Error loading [Reactor 1.2.0-rc.1] : Exception has been thrown by the target of an invocation.
 What do I do to fix this? Also, I'm on version 2021.11.9.5s

**Comment by js6pak** [comment]
[Update BepInEx](https://docs.reactor.gg/quick_start/install_bepinex)

**Comment by Medatur76** [comment]
I was watching [this](https://www.youtube.com/watch?v=XznJaOGh_74) and it told me to go [here](https://github.com/NuclearPowered/BepInEx/releases/tag/6.0.0-reactor.23) to get it, is tis ok or do I need to get it some where else?

**Comment by koxx12-dev** [comment]
> I was watching [this](https://www.youtube.com/watch?v=XznJaOGh_74) and it told me to go [here](https://github.com/NuclearPowered/BepInEx/releases/tag/6.0.0-reactor.23) to get it, is tis ok or do I need to get it some where else?

![firefox_GvWXGwxhIy](https://user-images.githubusercontent.com/80456351/146448727-2a2b88f7-1fa3-4450-bbbe-8fc077a2aa30.png)

just download the latest IL2CPP x86 version from [builds.bepis.io](https://builds.bepis.io/projects/bepinex_be) 
file name should be something like `BepInEx_UnityIL2CPP_x86_....zip` _as of writing this it would be `BepInEx_UnityIL2CPP_x86_30a1089_6.0.0-be.525.zip`_ and just follow the [docs](https://docs.reactor.gg/quick_start/install_bepinex/)
Also i wouldn't suggest using video guides because they are outdated like 99% of the time

**Comment by Medatur76** [comment]
I'm using a 64x Windows 11, so ould I get the 88x version or 64x version?

**Comment by koxx12-dev** [comment]
reading is a very useful thing

**Comment by Medatur76** [comment]
????

**Comment by koxx12-dev** [comment]
_download x86 one_

**Comment by Medatur76** [comment]
that got it working. Thx yall
