### ISSUE TITLE
2.0.0 not working on linux

### ISSUE THREAD

**Issue by Meindo** [NuclearPowered/Reactor#66]
Since version 2.0.0 moved to CoreCLR Among Us doesn't launch. In the debug console i see something about a newer wine version but since i have the game on steam i use proton and cant manually update wine. It looks like its running but it gets stuck on "[Il2CppInteropGen] Writing assemblies...". Anyone got 2.0.0 running on Linux?
system specs:
Artix Linux 6.0.6-artix1-1
KDE Plasma 5.26.2
Proton Experimental, Proton GE, Proton 7.04 tested.

**Comment by miniduikboot** [comment]
Hi there, unfortunately the version of BepInEx used by Reactor 2.0.0 crashes on old versions of Wine on first launch and while playing. The fix for this was included in WIne 6.16 but has not yet made it into Proton, [although I've opened a PR](https://github.com/ValveSoftware/wine/pull/162)

For Steam, you can either compile the branch my PR is based on, convince an uncle that works at Valve to merge that PR or [download my precompiled version](https://mini.duikbo.at/proton-7.0-4-bepinex.tar.xz)

For the Itch/Epic versions, you can install Wine 6.16 or higher and run the game via that, unfortunately for the Steam version that's not an option.

**Comment by Meindo** [comment]
Thanks, that worked! Closing this issue.
